---
title: "Proyecto Grupal - Herramientas de Ciencias de Datos II"
author: 
  - Estudiantes
  - Luis Fernando Amey Apuy - C20470
  - Javier Hernández Navarro - C13674
  - Anthony Mauricio Jiménez Navarro - C24067
date: "2024-05-13"
output: 
  rmdformats::downcute:
    default_style: "dark"
    downcute_theme: "chaos"
---

```{r, warning=FALSE}
library(jsonlite)
library(tidyverse)
library(lubridate)
setwd("..")
telegram <- fromJSON("data/herraI.json")
telegram <- as.data.frame(telegram$messages)
telegram <- telegram[telegram$type == "message",]
telegram$text[!is.na(telegram$photo)] <- 'photo'
telegram$text[!is.na(telegram$file)] <- 'file'
telegram$text[!is.na(telegram$media_type)] <- telegram$media_type[!is.na(telegram$media_type)]
telegram$edited[!is.na(telegram$edited)] <- TRUE
telegram <- telegram %>% select(id, date, text, from, edited, reply_to_message_id)
telegram <- telegram %>% separate(date, c('dia','hora'), sep = 'T')
telegram$dia <- ymd(telegram$dia)
telegram$hora <- hms(telegram$hora)
```

```{r}
spammer <- function(df){
  num <- df%>% count(from) %>% arrange(desc(n))
  return(num)
}
a<- spammer(telegram)
```

```{r}
dia_concurrido <- function(df){
    num <- df%>% count(dia) %>% arrange(desc(n))
  return(num)
}
a <- dia_concurrido(telegram)
```

```{r}
hora_concurrida <- function(df){
  df$hora <- hour(df$hora)
  num <- df %>% count(hora) %>% arrange(desc(n))
  return(num)
}
a <- hora_concurrida(telegram)
```

```{r}
streak_dias <- function(df){
  num <- unique(df$dia)
  dif <- num[1:length(num)-1] - num[2:length(num)]
  df <- data.frame(dif = dif)
  tabla <- df %>%
    mutate(is_target = dif == -1,               
           group = cumsum(!is_target)) %>%         
    group_by(group) 
  agrupados <- tabla %>%
    summarise(length = sum(is_target)) %>%         
    filter(length > 0) %>%arrange(desc(length))
  maximo <- agrupados[1,] 
  primerdia <- 0
  for(i in 1:length(tabla$group)){
    if (tabla$group[i]!= maximo$group | tabla$is_target[i] == FALSE){
      next
    } else {
      if (primerdia == 0){
        primerdia <- i
      }
      ultimodia <-i
    }
  }

  maximo <- maximo$length
  primerdia <- num[primerdia]
  ultimodia <- num[ultimodia+1]
  return(list(maximo, primerdia, ultimodia))
}
a <- streak_dias(telegram)
```



